version: "3.9"

services:
  web:
    volumes:
      - .:/var/www/app
      # TIMPA config HTTPS dengan config HTTP lokal
      - ./docker/nginx/default-local:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" # Buka port 80 saja di lokal
    # Hilangkan ketergantungan SSL jika perlu

  ai:
    # Di lokal, kita aktifkan volume agar perubahan kode Python langsung update
    volumes:
      - .:/app