version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: plantadvisor_app
    volumes:
      - .:/var/www/app
    env_file:
      - .env
    networks:
      - plantadvisor

  web:
    image: nginx:alpine
    container_name: plantadvisor_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf  # VPS HTTPS config
      - ./docker/nginx/certbot/www:/var/www/certbot
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - plantadvisor

  certbot:
    image: certbot/certbot
    container_name: plantadvisor_certbot
    volumes:
      - ./docker/nginx/certbot/www:/var/www/certbot
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;"
    networks:
      - plantadvisor

networks:
  plantadvisor:
    driver: bridge
