services:
  web:
    volumes:
      - .:/var/www/app
      # 1. Pastikan pakai .conf di sisi kiri
      - ./docker/nginx/default-local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  ai:
    volumes:
      - .:/app